/*
 * Author: Norbert Danisik
 *
 * Following block of code was added as an part of bachelor thesis.
 */
ifneq (,$(filter netdev_default gnrc_netdev_default gnrc_netif_default,$(USEMODULE)))
  USEMODULE += at86rf233
  USEMODULE += gnrc_nomac
endif


ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

